
-- VestiairePro v21 Supabase — base v13, sans IA photo
-- À lancer dans Supabase > SQL Editor.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nom text,
  status text default 'trial',
  trial_start timestamptz default now(),
  trial_end timestamptz default (now() + interval '24 hours'),
  last_login timestamptz,
  is_admin boolean default false,
  created_at timestamptz default now()
);

create table if not exists annonces (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  titre text,
  prix numeric,
  statut text default 'Actif',
  categorie text,
  vues int default 0,
  likes int default 0,
  messages int default 0,
  lien text,
  photo text,
  created_at timestamptz default now()
);

create table if not exists ventes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  titre text,
  prix numeric,
  acheteur text,
  statut text default 'En attente',
  categorie text,
  date_vente date default current_date,
  created_at timestamptz default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  type text,
  message text,
  lu boolean default false,
  created_at timestamptz default now()
);

create table if not exists user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table profiles enable row level security;
alter table annonces enable row level security;
alter table ventes enable row level security;
alter table notifications enable row level security;
alter table user_data enable row level security;

drop policy if exists "Lire son profil" on profiles;
drop policy if exists "Modifier son profil" on profiles;
drop policy if exists "Lire ses annonces" on annonces;
drop policy if exists "Ajouter ses annonces" on annonces;
drop policy if exists "Modifier ses annonces" on annonces;
drop policy if exists "Supprimer ses annonces" on annonces;
drop policy if exists "Lire ses ventes" on ventes;
drop policy if exists "Ajouter ses ventes" on ventes;
drop policy if exists "Modifier ses ventes" on ventes;
drop policy if exists "Supprimer ses ventes" on ventes;
drop policy if exists "Lire ses notifications" on notifications;
drop policy if exists "Ajouter ses notifications" on notifications;
drop policy if exists "Modifier ses notifications" on notifications;
drop policy if exists "Supprimer ses notifications" on notifications;
drop policy if exists "Lire ses données" on user_data;
drop policy if exists "Ajouter ses données" on user_data;
drop policy if exists "Mettre à jour ses données" on user_data;

create policy "Lire son profil" on profiles for select using (auth.uid() = id);
create policy "Modifier son profil" on profiles for update using (auth.uid() = id);
create policy "Lire ses annonces" on annonces for select using (auth.uid() = user_id);
create policy "Ajouter ses annonces" on annonces for insert with check (auth.uid() = user_id);
create policy "Modifier ses annonces" on annonces for update using (auth.uid() = user_id);
create policy "Supprimer ses annonces" on annonces for delete using (auth.uid() = user_id);
create policy "Lire ses ventes" on ventes for select using (auth.uid() = user_id);
create policy "Ajouter ses ventes" on ventes for insert with check (auth.uid() = user_id);
create policy "Modifier ses ventes" on ventes for update using (auth.uid() = user_id);
create policy "Supprimer ses ventes" on ventes for delete using (auth.uid() = user_id);
create policy "Lire ses notifications" on notifications for select using (auth.uid() = user_id);
create policy "Ajouter ses notifications" on notifications for insert with check (auth.uid() = user_id);
create policy "Modifier ses notifications" on notifications for update using (auth.uid() = user_id);
create policy "Supprimer ses notifications" on notifications for delete using (auth.uid() = user_id);
create policy "Lire ses données" on user_data for select using (auth.uid() = user_id);
create policy "Ajouter ses données" on user_data for insert with check (auth.uid() = user_id);
create policy "Mettre à jour ses données" on user_data for update using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, email, nom, status, trial_start, trial_end)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nom', split_part(new.email, '@', 1)),
    'trial',
    now(),
    now() + interval '24 hours'
  )
  on conflict (id) do nothing;

  insert into public.user_data (user_id, data)
  values (new.id, '{}'::jsonb)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Après avoir créé TON compte dans VestiairePro, remplace ton mail ci-dessous et lance :
-- update profiles set is_admin = true, status = 'paid' where email = 'tonmail@example.com';
